[project]
name = "de-zoomcamp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-api-core>=2.29.0",
    "google-cloud-storage>=2.16.0",
]

[tool.uv.workspace]
members = [
    "wk5_lesson_dlt",
]
