[project]
name = "wk5-lesson-dlt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "dlt[workspace]>=1.22.0",
    "ibis-framework[duckdb]>=12.0.0",
    "marimo>=0.20.1",
    "pandas>=3.0.1",
    "plotly>=6.5.2",
]
